/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prjArduino.interfaces;
import java.awt.Color;
import javax.swing.JOptionPane;
import prjarduino.ConexaoArdu;
import prjarduino.PrjArduino;

/**
 *
 * @author ProgSist
 */
public class TelaInicial extends javax.swing.JFrame {
    public boolean statuscasa, statustrabalho,ligado = false;
    public boolean ligadosala, ligadoquarto,ligadojardim,piscinaazul,piscinavermelha,piscinaverde,piscinaalternado; 
    
    ConexaoArdu inicio = new ConexaoArdu("COM4", 9600);
   
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButtononoff = new javax.swing.JButton();
        jCheckBoxcasa = new javax.swing.JCheckBox();
        jCheckBoxtrabalho = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenucontrole = new javax.swing.JMenu();
        jMenuItemSala = new javax.swing.JMenuItem();
        jMenuPiscina = new javax.swing.JMenu();
        jMenuItemAlternar = new javax.swing.JMenuItem();
        jMenuItemApagarP = new javax.swing.JMenuItem();
        jMenuItemVermelha = new javax.swing.JMenuItem();
        jMenuItemVerde = new javax.swing.JMenuItem();
        jMenuItemAzul = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemQuarto = new javax.swing.JMenuItem();
        jMenuItemsuite = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtononoff.setText("Ligar todas as luzes");
        jButtononoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtononoffActionPerformed(evt);
            }
        });

        jCheckBoxcasa.setSelected(true);
        jCheckBoxcasa.setText("Estou em casa");
        jCheckBoxcasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxcasaMouseClicked(evt);
            }
        });

        jCheckBoxtrabalho.setText("Estou no trabalho");
        jCheckBoxtrabalho.setEnabled(false);
        jCheckBoxtrabalho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxtrabalhoMouseClicked(evt);
            }
        });

        jButton1.setText("Ativar sensor");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de iluminação automatizado");

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Encerrar sistema");
        jMenu2.setEnabled(false);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenucontrole.setText("Controlar as luzes individualmente");

        jMenuItemSala.setText("Acender somente o Lounge");
        jMenuItemSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemSalaMouseClicked(evt);
            }
        });
        jMenuItemSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalaActionPerformed(evt);
            }
        });
        jMenucontrole.add(jMenuItemSala);

        jMenuPiscina.setText("Piscina");
        jMenuPiscina.setEnabled(false);

        jMenuItemAlternar.setText("Alternar Cores");
        jMenuItemAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlternarActionPerformed(evt);
            }
        });
        jMenuPiscina.add(jMenuItemAlternar);

        jMenuItemApagarP.setText("Apagar Piscina");
        jMenuItemApagarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApagarPActionPerformed(evt);
            }
        });
        jMenuPiscina.add(jMenuItemApagarP);

        jMenuItemVermelha.setText("Acender Luz Vermelha");
        jMenuItemVermelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVermelhaActionPerformed(evt);
            }
        });
        jMenuPiscina.add(jMenuItemVermelha);

        jMenuItemVerde.setText("Acender Luz Verde");
        jMenuItemVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerdeActionPerformed(evt);
            }
        });
        jMenuPiscina.add(jMenuItemVerde);

        jMenuItemAzul.setText("Acender Luz Azul");
        jMenuItemAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAzulActionPerformed(evt);
            }
        });
        jMenuPiscina.add(jMenuItemAzul);

        jMenucontrole.add(jMenuPiscina);

        jMenuItem2.setText("Acender somente jardim");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenucontrole.add(jMenuItem2);

        jMenuItemQuarto.setText("Acender somente a Quarto");
        jMenuItemQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartoActionPerformed(evt);
            }
        });
        jMenucontrole.add(jMenuItemQuarto);

        jMenuItemsuite.setText("Acender somente Suite");
        jMenuItemsuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsuiteActionPerformed(evt);
            }
        });
        jMenucontrole.add(jMenuItemsuite);

        jMenuBar1.add(jMenucontrole);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtononoff)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBoxtrabalho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(jCheckBoxcasa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxcasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxtrabalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtononoff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jCheckBoxcasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxcasaMouseClicked
        // TODO add your handling code here:
        statuscasa = true;
        statustrabalho = false;
        if (jCheckBoxtrabalho.isSelected()&&jCheckBoxcasa.isSelected())
        {
           jCheckBoxcasa.setSelected(true);
           jCheckBoxtrabalho.setSelected(false);
        }
        
    }//GEN-LAST:event_jCheckBoxcasaMouseClicked

    private void jCheckBoxtrabalhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxtrabalhoMouseClicked
        // TODO add your handling code here:
        statuscasa = false;
        statustrabalho = true;
        if (jCheckBoxcasa.isSelected()&&jCheckBoxtrabalho.isSelected())
        {
            jCheckBoxtrabalho.setSelected(true);
            jCheckBoxcasa.setSelected(false);
            
        }
    }//GEN-LAST:event_jCheckBoxtrabalhoMouseClicked

    private void jButtononoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtononoffActionPerformed
        // TODO add your handling code here:
       

        if (ligado == false)
        {
           ligado = true;
           inicio.enviaDados(1);
           inicio.enviaDados(3);
           inicio.enviaDados(5);
           jButtononoff.setText("Ligado, Clique para desligar tudo");
           jButtononoff.setForeground(Color.GREEN);
           
        }
        else
        {
            ligado = false;
            inicio.enviaDados(2);
            inicio.enviaDados(4);
            inicio.enviaDados(6);
            inicio.enviaDados(8);
            inicio.enviaDados(10);
            inicio.enviaDados(12);
            jButtononoff.setText("Ligado, Clique para desligar tudo");
            jButtononoff.setForeground(Color.red);
            try
            {
            Thread.sleep(200);
            }
            catch(Exception erro)
            {
                
            }
           jButtononoff.setText("Ligar todas as luzes");
           jButtononoff.setForeground(Color.BLACK);
            
            
        }
        
        
    }//GEN-LAST:event_jButtononoffActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
        inicio.close();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItemSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalaActionPerformed
        // TODO add your handling code here:
        if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        }
        else if (ligadosala == false)
        {
          ligadosala = true;
          inicio.enviaDados(1);
          System.err.println("dado enviado");
        }
        else 
        {
           ligadosala = false;
           inicio.enviaDados(2);
        }
    }//GEN-LAST:event_jMenuItemSalaActionPerformed

    private void jMenuItemSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSalaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItemSalaMouseClicked

    private void jMenuItemQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartoActionPerformed
        // TODO add your handling code here:
        if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        } 
           else if (ligadoquarto == false)
        {
          ligadoquarto = true;
          inicio.enviaDados(3);
          System.err.println("dado enviado");
        }
        else 
        {
           ligadoquarto = false;
           inicio.enviaDados(4);
        }
    }//GEN-LAST:event_jMenuItemQuartoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean A;
        A = true;
        while(A == true)
        {
        inicio.enviaDados(5);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
          boolean status;
        status = false;
        //if (status == false)
        //{
          inicio.enviaDados(7);
          System.err.println("dado enviado");
          status = true;
        //}
             if(status == true)
            {
                inicio.enviaDados(8);
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemVermelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVermelhaActionPerformed
        // TODO add your handling code here:
          if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        }
        else if (piscinavermelha == false)
        {
          piscinaverde=false;
          inicio.enviaDados(12);
          piscinaazul=false;
          inicio.enviaDados(8);
          piscinavermelha = true;
          inicio.enviaDados(9);
          System.err.println("dado enviado");
        }
        else 
        {
           piscinavermelha = false;
           inicio.enviaDados(10);
        }
      
        
    }//GEN-LAST:event_jMenuItemVermelhaActionPerformed

    private void jMenuItemAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlternarActionPerformed
        // TODO add your handling code here:
        // apagando todas as luzes antes de começar o ciclo
        inicio.enviaDados(8);
        inicio.enviaDados(10);
        inicio.enviaDados(12);
        int cont = 0;
        if(piscinaalternado==false){
           while(cont<10){
            try {
                    
                    piscinaazul=true;
                    inicio.enviaDados(7);
                    Thread.sleep(1000);
                    piscinaazul=false;
                    inicio.enviaDados(8);
                    piscinaverde=true;
                    inicio.enviaDados(11);
                    Thread.sleep(1000);
                    piscinaverde=false;
                    inicio.enviaDados(12);
                    piscinavermelha=true;
                    inicio.enviaDados(9);
                    Thread.sleep(1000);
                    piscinavermelha=false;
                    inicio.enviaDados(10);
                    cont++;
                } 
                catch (InterruptedException e) {
                    break;
                }
           }
           
        }
    }//GEN-LAST:event_jMenuItemAlternarActionPerformed

    private void jMenuItemVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerdeActionPerformed
        // TODO add your handling code here:
          if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        }
        else if (piscinaverde == false)
        {
          piscinavermelha=false;
          inicio.enviaDados(10);
          piscinaazul=false;
          inicio.enviaDados(8);
          piscinaverde = true;
          inicio.enviaDados(11);
          System.err.println("dado enviado");
        }
        else 
        {
           piscinaverde = false;
           inicio.enviaDados(12);
        }
    }//GEN-LAST:event_jMenuItemVerdeActionPerformed

    private void jMenuItemAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAzulActionPerformed
        // TODO add your handling code here:
          if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        }
        else if (piscinaazul == false)
        {
          piscinaverde=false;
          inicio.enviaDados(12);
          piscinavermelha=false;
          inicio.enviaDados(10);
          piscinaazul = true;
          inicio.enviaDados(7);
          System.err.println("dado enviado");
        }
        else 
        {
           piscinaazul = false;
           inicio.enviaDados(8);
        }
    }//GEN-LAST:event_jMenuItemAzulActionPerformed

    private void jMenuItemApagarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApagarPActionPerformed
        // TODO add your handling code here:
        inicio.enviaDados(8);
        inicio.enviaDados(10);
        inicio.enviaDados(12);
    }//GEN-LAST:event_jMenuItemApagarPActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        inicio.close();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemsuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsuiteActionPerformed
        // TODO add your handling code here:
       if(statustrabalho == true)
        {
           String teste =  JOptionPane.showInputDialog(null,"Sistema de segurança ativado ");
           switch (teste)
           {
               case "Admin" :statustrabalho = false;
               break;
           }
        } 
           else if (ligadoquarto == false)
        {
          ligadoquarto = true;
          inicio.enviaDados(5);
          System.err.println("dado enviado");
        }
        else 
        {
           ligadoquarto = false;
           inicio.enviaDados(6);
        }  
    }//GEN-LAST:event_jMenuItemsuiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtononoff;
    private javax.swing.JCheckBox jCheckBoxcasa;
    private javax.swing.JCheckBox jCheckBoxtrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAlternar;
    private javax.swing.JMenuItem jMenuItemApagarP;
    private javax.swing.JMenuItem jMenuItemAzul;
    private javax.swing.JMenuItem jMenuItemQuarto;
    private javax.swing.JMenuItem jMenuItemSala;
    private javax.swing.JMenuItem jMenuItemVerde;
    private javax.swing.JMenuItem jMenuItemVermelha;
    private javax.swing.JMenuItem jMenuItemsuite;
    private javax.swing.JMenu jMenuPiscina;
    private javax.swing.JMenu jMenucontrole;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
